platform :macos, '11.0'
use_modular_headers!

target 'GeoLoggerExampleMacOS' do
  pod 'GeoLoggerSDK',
    :path => '../../',
    :testspecs => ['Tests']
end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'GeoLoggerSDK'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '5'
            end
        end
    end
end
